CREATE TABLE [dbo].[Client](
    [mail] [varchar](50) NOT NULL,
    [nom] [varchar](50) NOT NULL,
    [prenom] [varchar](50) NOT NULL,
    CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED
(
[mail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]